### PR TITLE
Open branches sensitivity

### PR DESCRIPTION
**Pull request by flo-dup**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?**
No

**What kind of change does this PR introduce?**
Bug fix

**What is the current behavior?** 
Open branches sensitivity is
- 0 if contingency is breaking the connectivity
- 0 if contingency is not breaking the connectivity and the branch is in the main component
- NaN if contingency is not breaking the connectivity and the branch is not in the main component

**What is the new behavior (if this is a feature change)?**
Open branches sensitivity is always 0.

**Does this PR introduce a breaking change or deprecate an API?** 
No

### CODE REVIEW

**Comment by annetill** [comment]
The issue is more complex indeed, we have to follow the same logic as DC sensitivity analysis.

**Comment by annetill** [comment]
The issue is more complex indeed, we have to follow the same logic as DC sensitivity analysis.

**Comment by flo-dup** [comment]
Why don't we follow the same logic then? In the meantime it's strange to split this setPredefinedResults in parts instead of centralizing it, that was also the goal of this PR

**Comment by annetill** [comment]
> Why don't we follow the same logic then? In the meantime it's strange to split this setPredefinedResults in parts instead of centralizing it, that was also the goal of this PR

I think that the issue is more complex and has to be rethink more globally. As you said, I think that branch in contingency must be treated inside the predefined results. And we have to check what is done compared to DC sensitivity analysis. I have closed this PR but @Hadrien-Godard and me are going to reopen one, don't worry.

**Pull request closed without merging**
