### PR TITLE
First implementation of the Ward-injection reduction method

### PR DESCRIPTION
**Pull request by JB-H**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

New feature

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Comment by JB-H** [comment]
Dev tested on the ieee 14 with the following test example:

        LoadFlowParameters loadFlowParameters = LoadFlowParameters.load();
        Network networkPSSE = Importers.loadNetwork("<my path>\\IEEE_14_bus.raw");
        LoadFlowResult resultPsse = LoadFlow.run(networkPSSE, loadFlowParameters);

        List<String> voltageLevels = new ArrayList<>();
        voltageLevels.add("VL12");
        voltageLevels.add("VL13");

        OpenLoadFlowProvider olfp = new OpenLoadFlowProvider();
        OpenLoadFlowParameters parametersExt = olfp.getParametersExt(loadFlowParameters);
        olfp.runReduction(networkPSSE, loadFlowParameters, parametersExt, voltageLevels);

**Comment by JB-H** [comment]
I created in PowSyBl CORE the following pull request: Addition of a IEEE14 case builder #1707
This will help to build some test cases for unit tests of the reduction method.

**Comment by geofjamg** [comment]
> I created in PowSyBl CORE the following pull request: Addition of a IEEE14 case builder #1707
> This will help to build some test cases for unit tests of the reduction method.

There was already a IeeeNetworkFactory.create14() in the powsybl-ieee-converter module, what is the difference with your case?

**Comment by JB-H** [comment]
OK, I will remove the PR, I only looked in the iidm-test folder...

**Pull request closed without merging**
