### PR TITLE
Refactor separation of post contingency calculations in Woodbury DC Security Analysis

### PR DESCRIPTION
**Pull request by p-arvy**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No.

**What kind of change does this PR introduce?**

The distinction between post contingency result computation is refactored in Woodbury DC Security Analysis.

**What is the current behavior?**

In current behavior, code is duplicated. The only difference between the two calculations is the method used to calculate post contingency states (conditionned by post contingency connectivity result).

**What is the new behavior (if this is a feature change)?**
The code is mutualized. 

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

**Review by vidaldid-rte — CHANGES_REQUESTED** [review]
This is much better ! Thanks.  Can you remove the WIP ?

**Comment by p-arvy** [comment]
> This is much better ! Thanks. Can you remove the WIP ?

Thank you for the review. Done.

**Review by vidaldid-rte — APPROVED** [review]
As discussed with the team I would find it easier to read if the BiConsumer postContingencyResultAdder was instead defined as a method (because here we start reading runSimulations with this thing out of the calling context.
But OK to merge since this solves the issue of duplicated code.

**Comment by p-arvy** [comment]
> As discussed with the team I would find it easier to read if the BiConsumer postContingencyResultAdder was instead defined as a method (because here we start reading runSimulations with this thing out of the calling context. But OK to merge since this solves the issue of duplicated code.

Okay, thanks for the comment. I moved the BiConsumer `postContingencyResultAdder` into a method to simplify reading. This should also help to better manage the computation logic when we'll add actions.

**Pull request merged**
