### PR TITLE
Switch contingency support

### PR DESCRIPTION
**Pull request by geofjamg**
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Review by annetill — COMMENTED** [review]
What about the impact on sensitivity analysis? As we are in bus view for sensitivity analysis (right?), we will fall in the exception?

**Comment by geofjamg** [comment]
> What about the impact on sensitivity analysis? As we are in bus view for sensitivity analysis (right?), we will fall in the exception?

I have to test it. For DC sensitivity analysis it is same issue as for contingency propagation: so it is an ongoing topic.
For AC sensitivity analysis it should work without any problem as we rebuild the jacobian matrix for each contingency => to test

**Comment by geofjamg** [comment]
> > What about the impact on sensitivity analysis? As we are in bus view for sensitivity analysis (right?), we will fall in the exception?
> 
> I have to test it. For DC sensitivity analysis it is same issue as for contingency propagation: so it is an ongoing topic. For AC sensitivity analysis it should work without any problem as we rebuild the jacobian matrix for each contingency => to test

I just threw an exception in case of sensitivity analysis. As calculation is done on bus/view (breakers = false in DC and in AC), there is a LOT a work to make it working for sensitivity analysis and not sure somebody needs it. So let's see that later.

**Review by annetill — APPROVED** [review]
Yes, later for sensitivity analysis !

**Pull request merged**
