### PR TITLE
Retrieve specific parameters overrides from PlatformConfig

### PR DESCRIPTION
**Pull request by antoinebhs**
**Requires next powsybl upgrade**

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
https://github.com/powsybl/powsybl-core/issues/3066

### CODE REVIEW

**Comment by antoinebhs** [comment]
@SylvestreSakti, this requires the next powsybl upgrade

**Comment by SylvestreSakti** [comment]
> @SylvestreSakti, this requires the next powsybl upgrade

Yes, ok, now I understand that the checks will work with the next release of core.

**Review by jeandemanged — DISMISSED** [review]
Looking at https://github.com/powsybl/powsybl-core/issues/3066 we should probably apply the change as well to:
- `open-security-analysis-default-parameters`
- `open-sensitivityanalysis-default-parameters`

right ?

**Comment by olperr1** [comment]
> Looking at [powsybl/powsybl-core#3066](https://github.com/powsybl/powsybl-core/issues/3066) we should probably apply the change as well to:
> 
>     * `open-security-analysis-default-parameters`
> 
>     * `open-sensitivityanalysis-default-parameters`
> 
> 
> right ?

@jeandemanged: You are right... but these providers were forgotten in powsybl/powsybl-core#3133.

**Comment by olperr1** [comment]
> I will open an issue in `powsybl-core` on this subject, but for now these providers shouldn't be updated.

The issue is here: powsybl/powsybl-core#3175

**Review by geofjamg — APPROVED** [review]

**Pull request merged**
